package ppp.ui;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JToggleButton;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import ppp.HyperEdge;
import ppp.HyperEdge2;
import ppp.HyperGraph;

/**
 *
 * @author eullah01
 */
@SuppressWarnings({"rawtypes", "serial", "unchecked"})
public class GraphDisplayDialog extends javax.swing.JDialog implements CellEditorListener, WindowListener {

   private final JToggleButton viewButton;
   private final DefaultTableModel dataModel;
   private HyperGraph graph;

   public GraphDisplayDialog(java.awt.Frame parent, String title, JToggleButton viewButton) {
      super(parent, title, false);
      this.viewButton = viewButton;
      initComponents();
      this.resizeColumns();
      this.dataModel = (DefaultTableModel) this.tblGraph.getModel();
      this.initListeners();
   }

   private void initListeners() {
      this.tblGraph.getDefaultEditor(String.class).addCellEditorListener(this);
      this.addWindowListener(this);
   }

   public void setGraph(HyperGraph g) {
      this.graph = g;
      ArrayList<HyperEdge> edges = g.getEdges();
      this.dataModel.setRowCount(edges.size());
      for (int i = 0; i < edges.size(); i++) {
         HyperEdge edge = edges.get(i);
         int c = 0;
         this.dataModel.setValueAt("" + (i + 1), i, c++);
         this.dataModel.setValueAt(edge.getName(), i, c++);
         this.dataModel.setValueAt(edge.getWeight(), i, c++);
         this.dataModel.setValueAt(((HyperEdge2) edge).getMinWeight(), i, c++);
         this.dataModel.setValueAt(((HyperEdge2) edge).getMaxWeight(), i, c++);
         this.dataModel.setValueAt(edge.getEquation(), i, c++);
      }
      this.resizeColumns();
   }

   private void resizeColumns() {
      int cId = 0;
      int width = 40;
      this.tblGraph.getColumnModel().getColumn(cId).setMinWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId++).setMaxWidth(width);
      width = 75;
      this.tblGraph.getColumnModel().getColumn(cId).setMinWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId++).setMaxWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId).setMinWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId++).setWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId).setMinWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId++).setWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId).setMinWidth(width);
      this.tblGraph.getColumnModel().getColumn(cId++).setWidth(width);
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {
      java.awt.GridBagConstraints gridBagConstraints;

      spGraph = new javax.swing.JScrollPane();
      tblGraph = new javax.swing.JTable();

      getContentPane().setLayout(new java.awt.GridBagLayout());

      tblGraph.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Sr No.", "Name", "Weight", "Min Value", "Max Value", "Equation"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, true, true, true, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tblGraph.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
      spGraph.setViewportView(tblGraph);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
      gridBagConstraints.weightx = 1.0;
      gridBagConstraints.weighty = 1.0;
      gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
      getContentPane().add(spGraph, gridBagConstraints);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   @Override
   public void editingStopped(ChangeEvent e) {
      int row = this.tblGraph.getSelectedRow();
      int column = this.tblGraph.getSelectedColumn();
      HyperEdge2 edge = (HyperEdge2) this.graph.getEdges().get(row);
      double value = 0;
      try {
         switch (column) {
            case 2:
               value = edge.getWeight();
               edge.setWeight(Double.parseDouble(this.tblGraph.getValueAt(row, column).toString()));
               break;
            case 3:
               value = edge.getMinWeight();
               edge.setMinWeight(Double.parseDouble(this.tblGraph.getValueAt(row, column).toString()));
               break;
            case 4:
               value = edge.getMaxWeight();
               edge.setMaxWeight(Double.parseDouble(this.tblGraph.getValueAt(row, column).toString()));
               break;
         }
      } catch (NumberFormatException ex) {
         this.tblGraph.setValueAt("" + value, row, column);
      }
   }

   @Override
   public void editingCanceled(ChangeEvent e) {
   }

   // <editor-fold defaultstate="collapsed" desc="WindowListener">
   @Override
   public void windowOpened(WindowEvent e) {
   }

   @Override
   public void windowClosing(WindowEvent e) {
      this.viewButton.setSelected(false);
   }

   @Override
   public void windowClosed(WindowEvent e) {
   }

   @Override
   public void windowIconified(WindowEvent e) {
   }

   @Override
   public void windowDeiconified(WindowEvent e) {
   }

   @Override
   public void windowActivated(WindowEvent e) {
   }

   @Override
   public void windowDeactivated(WindowEvent e) {
   }// </editor-fold>
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane spGraph;
   private javax.swing.JTable tblGraph;
   // End of variables declaration//GEN-END:variables
}
